name: one_line_shimmer
description: >
  A lightweight and customizable one-line shimmer widget for Flutter apps.
  Supports custom colors, animation speed, and rounded borders.

version: 1.0.3
homepage: https://github.com/Abdulrhman-Khaled/one_line_shimmer
repository: https://github.com/Abdulrhman-Khaled/one_line_shimmer
issue_tracker: https://github.com/Abdulrhman-Khaled/one_line_shimmer/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

